// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPPVwTF8s6hK7lrOaL2qmqBrkSrWyyKU',
    appId: '1:949945299701:web:91edac9b999b326948cbbc',
    messagingSenderId: '949945299701',
    projectId: 'patokatu-38edf',
    authDomain: 'patokatu-38edf.firebaseapp.com',
    storageBucket: 'patokatu-38edf.appspot.com',
    measurementId: 'G-6ZZZJM1JKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NOXCBlkDP1XLlltTMichej-5IaIDMMI',
    appId: '1:949945299701:android:0cf9aba852d1cb5648cbbc',
    messagingSenderId: '949945299701',
    projectId: 'patokatu-38edf',
    storageBucket: 'patokatu-38edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhSZYLn9FRF0n64bJEuYVNA5Kiy4_imI',
    appId: '1:949945299701:ios:f099eca1f47af08a48cbbc',
    messagingSenderId: '949945299701',
    projectId: 'patokatu-38edf',
    storageBucket: 'patokatu-38edf.appspot.com',
    iosBundleId: 'com.example.patokatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhSZYLn9FRF0n64bJEuYVNA5Kiy4_imI',
    appId: '1:949945299701:ios:02629a33ce97870548cbbc',
    messagingSenderId: '949945299701',
    projectId: 'patokatu-38edf',
    storageBucket: 'patokatu-38edf.appspot.com',
    iosBundleId: 'com.example.patokatu.RunnerTests',
  );
}
